name: Deploy

on:
  push:
    branches: [master, project_5, final_project]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "frens-app"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
